import React,{useEffect,useMemo,useRef,useState}from'react';
import'./evidence.css';
import{createClient}from'genlayer-js';import{studionet}from'genlayer-js/chains';import{TransactionStatus}from'genlayer-js/types';
import{Activity,AlertTriangle,ArrowUpRight,BookOpen,CheckCircle2,ChevronRight,Clock3,ExternalLink,GitBranch,Plus,Radio,RefreshCcw,Route,Send,ShieldCheck,TerminalSquare,UserRoundCheck,Wallet}from'lucide-react';

const CONTRACT=import.meta.env.VITE_CONTRACT_ADDRESS||'';const configured=/^0x[a-fA-F0-9]{40}$/.test(CONTRACT)&&!/^0x0{40}$/.test(CONTRACT);const EXPLORER='https://explorer-studio.genlayer.com';const REPOSITORY='https://github.com/Azaria723/RunbookRouter';const EVIDENCE=`${REPOSITORY}/blob/master/verification/studionet-verification.md`;const MATRIX=`${REPOSITORY}/blob/master/verification/adversarial-test-matrix.md`;const client=()=>createClient({chain:studionet});const compact=(v='')=>v.length>15?`${v.slice(0,7)}…${v.slice(-5)}`:v;
const initialService={key:'bridge-mainnet',responder:'',owner:'Azaria723',repo:'RunbookRouter',ack:'600'};
const initialRunbook={serviceId:'0',key:'bridge-withdrawal',revision:'1',commit:'',path:'/evidence/runbooks/bridge-withdrawal.md',digest:'',classes:'["WITHDRAWAL_DEGRADATION"]',severities:'["HIGH","CRITICAL"]',actions:'["pause-outbound-queue"]'};
const initialIncident={serviceId:'0',component:'withdrawal-relayer',description:'Withdrawals have remained pending for forty minutes while deposits still succeed.'};

export default function App(){const[account,setAccount]=useState(''),[counts,setCounts]=useState({service_count:0,version_count:0,incident_count:0}),[services,setServices]=useState([]),[versions,setVersions]=useState([]),[incidents,setIncidents]=useState([]),[selected,setSelected]=useState(0),[panel,setPanel]=useState('incident'),[service,setService]=useState(initialService),[runbook,setRunbook]=useState(initialRunbook),[draft,setDraft]=useState(initialIncident),[mitigation,setMitigation]=useState('Paused affected operation and started the verified diagnostic checklist.'),[resolution,setResolution]=useState('Service health recovered and the original failure mode is no longer observed.'),[notice,setNotice]=useState('Operations feed ready.'),[tx,setTx]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false);
 const read=async(name,args=[])=>JSON.parse(await client().readContract({address:CONTRACT,functionName:name,args}));
 async function refresh(){if(!configured)return;const next=await read('get_counts');setCounts(next);const[s,v,i]=await Promise.all([Promise.all(Array.from({length:next.service_count},(_,n)=>read('get_service',[BigInt(n)]))),Promise.all(Array.from({length:next.version_count},(_,n)=>read('get_version',[BigInt(n)]))),Promise.all(Array.from({length:next.incident_count},(_,n)=>read('get_incident',[BigInt(n)])))]);setServices(s);setVersions(v);setIncidents(i);if(i.length)setSelected(x=>Math.min(x,i.length-1));}
 useEffect(()=>{refresh().catch(e=>setNotice(e.message));const eth=window.ethereum,changed=a=>setAccount(a[0]||'');eth?.request({method:'eth_accounts'}).then(changed).catch(()=>{});eth?.on?.('accountsChanged',changed);return()=>eth?.removeListener?.('accountsChanged',changed)},[]);
 async function connect(){try{if(!window.ethereum)throw Error('Install a compatible wallet.');setAccount((await window.ethereum.request({method:'eth_requestAccounts'}))[0]||'')}catch(e){setNotice(e.message)}}
 async function write(name,args){if(lock.current)return;lock.current=true;setBusy(true);setTx('');try{if(!configured)throw Error('Contract address is not configured yet.');if(!account)throw Error('Connect a wallet first.');if(BigInt(await window.ethereum.request({method:'eth_chainId'}))!==61999n)throw Error('Switch wallet to StudioNet chain 61999.');const writer=createClient({chain:studionet,provider:window.ethereum,account});setNotice(`Awaiting ${name} confirmation…`);const hash=await writer.writeContract({address:CONTRACT,functionName:name,args});setTx(hash);setNotice('Transaction submitted. Waiting for finality…');await client().waitForTransactionReceipt({hash,status:TransactionStatus.FINALIZED});await refresh();setNotice(`${name} finalized and the dispatch board was refreshed.`)}catch(e){setNotice(e.message)}finally{setBusy(false);lock.current=false}}
 function createService(e){e.preventDefault();write('create_service',[service.key,service.responder,service.owner,service.repo,BigInt(service.ack)])}
 function publish(e){e.preventDefault();try{JSON.parse(runbook.classes);JSON.parse(runbook.severities);JSON.parse(runbook.actions)}catch{return setNotice('Taxonomy fields must be valid JSON arrays.')}write('publish_runbook',[BigInt(runbook.serviceId),runbook.key,BigInt(runbook.revision),runbook.commit,runbook.path,runbook.digest,runbook.classes,runbook.severities,runbook.actions])}
 function openIncident(e){e.preventDefault();write('open_incident',[BigInt(draft.serviceId),draft.component,draft.description,BigInt(Math.floor(Date.now()/1000))])}
 const active=incidents[selected];const activeService=active&&services[active.service_id];const activeVersion=active?.selected_version_id>=0?versions[active.selected_version_id]:null;const urgent=incidents.filter(x=>['OPEN','ROUTED','ESCALATED'].includes(x.status)).length;const routed=incidents.filter(x=>x.status==='ROUTED').length;
 const steps=useMemo(()=>active?['OPEN','ROUTED','ACKNOWLEDGED','MITIGATING','RESOLVED'].map((name,index)=>({name,done:index<=['OPEN','ROUTED','ACKNOWLEDGED','MITIGATING','RESOLVED'].indexOf(active.status)})):[],[active]);
 return <div className="shell"><header><a className="wordmark" href="#top"><img src="/logo.png" alt="RunbookRouter logo"/><div><b>RunbookRouter</b><small>INCIDENT DISPATCH</small></div></a><div className="network"><i/>StudioNet · 61999</div><a className="contract" href={configured?`${EXPLORER}/address/${CONTRACT}`:'#'} target="_blank" rel="noopener noreferrer">{configured?compact(CONTRACT):'Awaiting contract'} <ArrowUpRight/></a><button className="wallet" onClick={connect}><Wallet/>{account?compact(account):'Connect wallet'}</button></header>
 <main id="top"><section className="mast"><div><p><Radio/> LIVE OPERATIONS LAYER</p><h1>Route incidents to<br/><em>verified response.</em></h1><span>Validators match operational symptoms against digest-bound runbooks. Responders own execution; reporters confirm recovery.</span></div><div className="mast-art"><img src="/logo.png" alt="RunbookRouter incident routing logo"/><div className="pulse"><i/><span>Routing engine</span><b>{configured?'ONLINE':'STANDBY'}</b></div></div></section>
 <section className="metrics"><Metric icon={<AlertTriangle/>} label="Needs attention" value={urgent}/><Metric icon={<Route/>} label="Awaiting response" value={routed}/><Metric icon={<BookOpen/>} label="Runbook versions" value={counts.version_count}/><Metric icon={<CheckCircle2/>} label="Resolved" value={incidents.filter(x=>x.status==='RESOLVED').length}/></section>
 <div className="dispatch"><aside className="queue"><div className="panel-title"><div><small>01 / INCIDENT QUEUE</small><h2>Dispatch feed</h2></div><button onClick={()=>refresh().catch(e=>setNotice(e.message))}><RefreshCcw/></button></div><div className="filters"><button className="active">All {counts.incident_count}</button><button>Active {urgent}</button></div><div className="queue-list">{incidents.length?incidents.map((item,index)=><button key={item.incident_id} className={selected===index?'selected':''} onClick={()=>setSelected(index)}><span className={`severity ${item.severity||'UNROUTED'}`}>{item.severity||'NEW'}</span><div><b>{item.component}</b><small>INC-{String(item.incident_id).padStart(4,'0')} · {item.status}</small></div><ChevronRight/></button>):<div className="no-items"><Activity/><b>No incidents yet</b><span>Open the first report from the command panel.</span></div>}</div></aside>
 <section className="focus"><small className="section-kicker">02 / ROUTE DETAIL</small>{active?<><div className="focus-head"><div><span className={`status ${active.status}`}>{active.status}</span><small>INC-{String(active.incident_id).padStart(4,'0')}</small><h2>{active.component}</h2><p>{active.description}</p></div><div className="severity-card"><small>SEVERITY</small><b>{active.severity||'UNASSESSED'}</b><span>{active.confidence?`${active.confidence} confidence`:'Routing not started'}</span></div></div><div className="route-map"><div className="route-source"><AlertTriangle/><span>Signal received</span><b>{active.component}</b></div><div className="route-line"><i/><Route/><i/></div><div className="route-target"><BookOpen/><span>Selected playbook</span><b>{activeVersion?`${activeVersion.runbook_key} · r${activeVersion.revision}`:'Awaiting semantic route'}</b></div></div>{active.initial_action&&<div className="action-callout"><TerminalSquare/><div><small>INITIAL ACTION</small><b>{active.initial_action}</b></div><ShieldCheck/><span>Source verified</span></div>}<div className="timeline">{steps.map(step=><div key={step.name} className={step.done?'done':''}><i>{step.done?<CheckCircle2/>:<Clock3/>}</i><span>{step.name}</span></div>)}</div></>:<div className="blank-focus"><img src="/logo.png"/><small>NO ACTIVE SIGNAL</small><h2>Your incident route will appear here.</h2><p>Create a service and publish runbooks, then open a report from the command panel.</p></div>}</section>
 <aside className="commands"><div className="panel-title"><div><small>03 / COMMAND PANEL</small><h2>Take action</h2></div></div><div className="tabs"><button className={panel==='incident'?'active':''} onClick={()=>setPanel('incident')}>Report</button><button className={panel==='catalog'?'active':''} onClick={()=>setPanel('catalog')}>Catalog</button><button className={panel==='service'?'active':''} onClick={()=>setPanel('service')}>Service</button></div>{panel==='incident'&&<form onSubmit={openIncident}><Field label="Service ID" type="number" value={draft.serviceId} set={v=>setDraft({...draft,serviceId:v})}/><Field label="Affected component" value={draft.component} set={v=>setDraft({...draft,component:v})}/><Area label="Observed symptoms" value={draft.description} set={v=>setDraft({...draft,description:v})}/><button className="primary" disabled={busy}><Plus/> Open incident</button></form>}{panel==='service'&&<form onSubmit={createService}><Field label="Service key" value={service.key} set={v=>setService({...service,key:v})}/><Field label="Responder address" value={service.responder} set={v=>setService({...service,responder:v})}/><div className="two"><Field label="GitHub owner" value={service.owner} set={v=>setService({...service,owner:v})}/><Field label="Repository" value={service.repo} set={v=>setService({...service,repo:v})}/></div><Field label="Ack window · seconds" type="number" value={service.ack} set={v=>setService({...service,ack:v})}/><button className="primary" disabled={busy}><Plus/> Register service</button></form>}{panel==='catalog'&&<form onSubmit={publish}><div className="two"><Field label="Service ID" type="number" value={runbook.serviceId} set={v=>setRunbook({...runbook,serviceId:v})}/><Field label="Revision" type="number" value={runbook.revision} set={v=>setRunbook({...runbook,revision:v})}/></div><Field label="Runbook key" value={runbook.key} set={v=>setRunbook({...runbook,key:v})}/><Field label="Full commit SHA" value={runbook.commit} set={v=>setRunbook({...runbook,commit:v})}/><Field label="Canonical path" value={runbook.path} set={v=>setRunbook({...runbook,path:v})}/><Field label="Content SHA-256" value={runbook.digest} set={v=>setRunbook({...runbook,digest:v})}/><Area label="Incident classes JSON" value={runbook.classes} set={v=>setRunbook({...runbook,classes:v})}/><Area label="Severities JSON" value={runbook.severities} set={v=>setRunbook({...runbook,severities:v})}/><Area label="Actions JSON" value={runbook.actions} set={v=>setRunbook({...runbook,actions:v})}/><button className="primary" disabled={busy}><GitBranch/> Publish revision</button></form>}</aside></div>
 {active&&<section className="response"><div><small>04 / RESPONSE CONTROL</small><h2>Move the incident forward</h2><p>Routing recommends a verified starting point. Only the assigned responder can acknowledge and record mitigation; the reporter confirms resolution.</p></div><div className="response-actions"><button disabled={busy||active.status!=='OPEN'} onClick={()=>write('route_incident',[BigInt(active.incident_id)])}><Route/> Route now</button><button disabled={busy||active.status!=='ROUTED'} onClick={()=>write('acknowledge',[BigInt(active.incident_id)])}><UserRoundCheck/> Acknowledge</button><label>Mitigation note<input value={mitigation} onChange={e=>setMitigation(e.target.value)}/><button disabled={busy||!['ACKNOWLEDGED','MITIGATING'].includes(active.status)} onClick={()=>write('record_mitigation',[BigInt(active.incident_id),mitigation])}><Send/> Record</button></label><label>Resolution note<input value={resolution} onChange={e=>setResolution(e.target.value)}/><button disabled={busy||active.status!=='MITIGATING'} onClick={()=>write('resolve',[BigInt(active.incident_id),resolution])}><CheckCircle2/> Resolve</button></label></div></section>}
 <div className="console"><span><i className={busy?'busy':''}/>{notice}</span>{tx&&<a href={`${EXPLORER}/tx/${tx}`} target="_blank" rel="noopener noreferrer">Inspect transaction <ExternalLink/></a>}</div></main><footer><div><span>RUNBOOKROUTER / GENLAYER</span><p>Semantic routing is advisory. Workflow authority remains deterministic and role-bound.</p></div><nav><a href={EVIDENCE} target="_blank" rel="noopener noreferrer"><ShieldCheck/>StudioNet proof</a><a href={MATRIX} target="_blank" rel="noopener noreferrer"><CheckCircle2/>44 adversarial checks</a><a href={REPOSITORY} target="_blank" rel="noopener noreferrer"><GitBranch/>Source</a></nav></footer></div>}

function Metric({icon,label,value}){return <article>{icon}<div><small>{label}</small><b>{value}</b></div></article>}function Field({label,value,set,type='text'}){return <label>{label}<input type={type} value={value} onChange={e=>set(e.target.value)}/></label>}function Area({label,value,set}){return <label>{label}<textarea value={value} onChange={e=>set(e.target.value)}/></label>}
